export const DESTINATION_ACTION_TYPES = {
    GET_DESTINATIONS: 'GET_DESTINATIONS',
    GET_DESTINATIONS_SUCCESS: 'GET_DESTINATIONS_SUCCESS',
    GET_DESTINATIONS_FAILED: 'GET_DESTINATIONS_FAILED'
};
